In [1]:
import pickle

import datetime
import pandas as pd

from data.dao import DataAccess, LabelGetter
from data.turk import TurkResults2Label

In [2]:
import os

In [6]:
folder = 'E:/Sept-March 2015/csv with offset/sept amt'
tweets = pd.DataFrame()
for file in os.listdir(folder):
    df = pd.read_csv(folder + '/' + file, engine='python')
    tweets = pd.concat([tweets, df])

In [7]:
tweets.shape

(682931, 7)

In [ ]:
import re

In [8]:
keywords = set('''drink drinker drinks drinking drank wine champgne alcohol alcoholics alcoholism beer beers bottle bottles
    pint pints cocktail cocktails bar brewery lounge pub liquor booze vodka tequila gin ciroc margarita margaritas shot shots
    ale whiskey lager tipsy drunk sober wasted pregame pregaming'''.split())

def prefilter(text):
    return bool(set(text.split()).intersection(keywords))

In [12]:
tweets.text.shape

(682931,)

In [13]:
filtered = tweets[tweets.text.apply(prefilter)]

In [16]:
filtered.sample(1000)

,Unnamed: 0,text,id,created_at,lat,lon,utc_offset
95402,23211,Teen drinking is very bad,648035279631085569,Sun Sep 27 07:23:45 +0000 2015,43.068737,-88.540000,NaN
55843,54590,so pour a shot in my glass and I'll forget for...,640984252180484096,Mon Sep 07 20:25:29 +0000 2015,30.144425,-88.473228,NaN
24112,92816,@CynthiaNewsome it depends on what day. Someti...,643511933669371908,Mon Sep 14 19:49:35 +0000 2015,38.868002,-94.845486,NaN
62895,155721,Helllooo new #wine bar discovery!! Let there b...,641067852146061312,Tue Sep 08 01:57:41 +0000 2015,32.539620,-117.282538,-25200.0
27258,109973,Kim engaged?? What that open bar like DOE?,646909652081381377,Thu Sep 24 04:50:54 +0000 2015,33.825123,-84.348581,-21600.0
9864,64208,"Ivory Ella's water bottles are sold out, and i...",643248685502066688,Mon Sep 14 02:23:32 +0000 2015,30.144425,-88.473228,NaN
70084,49661,@valsingerr lol ya I drink so I can love you,649274616389718016,Wed Sep 30 17:28:26 +0000 2015,41.117660,-81.392451,-10800.0
38161,14495,JB bought a drink that is supposedly a muscle ...,643652141966589952,Tue Sep 15 05:06:43 +0000 2015,27.386503,-82.459348,-18000.0
61057,16594,"@g0ldieex thank you very much, come out for dr...",644015026295209984,Wed Sep 16 05:08:42 +0000 2015,33.845960,-118.108568,-25200.0
72914,65104,#Mcm goes out to lfrancoeur96 the best beer po...,646104533127557120,Mon Sep 21 23:31:39 +0000 2015,44.961937,-76.353876,NaN
74864,68920,Drink tequila for me babe,646118732985724928,Tue Sep 22 00:28:04 +0000 2015,42.674424,-73.998477,-25200.0
67214,9963,@PerezHilton bc anything to do with drugs or a...,639589755278237696,Fri Sep 04 00:04:15 +0000 2015,33.688539,-84.794814,NaN
86168,63998,Always remember Han shot first #starwars #HanS...,646333802961203201,Tue Sep 22 14:42:41 +0000 2015,33.788913,-118.017789,NaN
41025,13098,@johnnyymvdrid lmao the only thing i was simpi...,648758873373831168,Tue Sep 29 07:19:03 +0000 2015,33.802102,-117.672915,-25200.0
3276,40624,maria i'm drunk â€¢ travi$ scott ft. justin bi...,643186989899059201,Sun Sep 13 22:18:22 +0000 2015,34.712551,-77.362653,-18000.0
31336,22076,Lets see how these beers taste after all day d...,640603023081930752,Sun Sep 06 19:10:37 +0000 2015,36.672684,-76.228080,NaN
38565,66837,#Winewednesday we luv U. #WineOclock #happyhou...,639189362337579008,Wed Sep 02 21:33:14 +0000 2015,40.477383,-79.762590,-14400.0
55744,57705,Fancy cocktails #sundaybrunch #gin #lavender #...,645679996317503488,Sun Sep 20 19:24:41 +0000 2015,32.528832,-124.482003,-25200.0
34786,74203,@_wildfire__ same shit haha but fuck it i aint...,642133031986200576,Fri Sep 11 00:30:19 +0000 2015,39.838926,-105.015543,-18000.0
17317,49199,If you wanna fill your bottle up with lightnin...,641844864204718080,Thu Sep 10 05:25:15 +0000 2015,33.290260,-112.323914,NaN
22899,14806,"@NateFerris44 Hi Nate ... no, these pix belong...",643486413028200448,Mon Sep 14 18:08:10 +0000 2015,42.826008,-78.912276,-14400.0
95905,4726,Do I drink these beers or no?,648062376248344576,Sun Sep 27 09:11:25 +0000 2015,47.110842,-122.415738,-25200.0
29888,84307,In need of a beer and cigar,645291381129355264,Sat Sep 19 17:40:28 +0000 2015,40.495865,-74.255641,NaN
29282,60355,It just hit me I probably won't ever have anot...,646941564149739520,Thu Sep 24 06:57:43 +0000 2015,37.845953,-122.324818,-10800.0
9485,89212,I love alexis I gave her my bar,640263746087051264,Sat Sep 05 20:42:27 +0000 2015,35.994510,-87.022482,-14400.0
90059,61589,Someone should pour me up a drink,646376833613721601,Tue Sep 22 17:33:40 +0000 2015,26.119383,-80.363112,-25200.0
84667,23553,"I bought this in Chicago, figured it was time ...",641388256249163777,Tue Sep 08 23:10:51 +0000 2015,42.526050,-83.441942,-14400.0
75889,4359,I'm wearing combat boots and drinking a frap a...,644285118534799360,Wed Sep 16 23:01:57 +0000 2015,24.396308,-87.634643,-14400.0
52065,14254,Need about 10 shots right now,643909033880121344,Tue Sep 15 22:07:31 +0000 2015,42.988257,-78.696944,NaN
44433,59422,Going through my pictures and not knowing some...,648869954310270976,Tue Sep 29 14:40:27 +0000 2015,39.584088,-79.987463,NaN
...,...,...,...,...,...,...,...
98553,12148,"I need a pizza, a bottle of whiskey, an island...",648151987884724224,Sun Sep 27 15:07:30 +0000 2015,31.455070,-97.268990,NaN
58991,110733,"Everyday I spend my time drinking wine, feelin...",641021468520771584,Mon Sep 07 22:53:22 +0000 2015,41.175884,-96.234587,-18000.0
52026,16086,It's not OK I am totally against it. By no mea...,648967677688463360,Tue Sep 29 21:08:46 +0000 2015,38.200638,-104.693560,NaN
63207,34009,When you look across the bar and make eye cont...,642552021632028672,Sat Sep 12 04:15:14 +0000 2015,39.052962,-84.710722,-28800.0
69221,12316,Let me enjoy some free beer on my Sunday.. Hap...,644195670019190784,Wed Sep 16 17:06:30 +0000 2015,33.704538,-118.668404,NaN
89303,52036,It's always cute when girls who should be at h...,642949356690272256,Sun Sep 13 06:34:06 +0000 2015,28.388218,-81.507905,-14400.0
46715,53756,sooo my mom put my slush from sonic in the fre...,647234240648622080,Fri Sep 25 02:20:42 +0000 2015,32.563973,-97.078573,NaN
67646,55478,@jrmyrdrr drinking an arizona and playing nhl ...,639609211727532032,Fri Sep 04 01:21:34 +0000 2015,41.868615,-70.977086,-14400.0
56585,121973,i dont sip wine i chug it,643979082057670656,Wed Sep 16 02:45:52 +0000 2015,35.153270,-97.519820,-18000.0
39819,65707,@kerryryanxx road trip I'm just having drinks,645409227842940928,Sun Sep 20 01:28:45 +0000 2015,40.888371,-73.072409,-18000.0
33832,84996,You have to RT @Gezzy504: If I bring a bottle ...,647075015142146048,Thu Sep 24 15:48:00 +0000 2015,29.638972,-91.149020,-18000.0
96036,71084,When u drunk with ur homie and climb walls and...,644611344805707778,Thu Sep 17 20:38:15 +0000 2015,34.117025,-118.198346,NaN
96892,25489,"Said I wasn't going out tonight, so my friends...",644620228895313921,Thu Sep 17 21:13:33 +0000 2015,35.001706,-81.046876,-14400.0
21736,93190,"Did you know, drinking soda before bed gives y...",646846591480033280,Thu Sep 24 00:40:19 +0000 2015,41.603903,-71.195676,-18000.0
50312,101570,"I was drinking that white remy lastnight, I th...",645627693011177472,Sun Sep 20 15:56:51 +0000 2015,41.401871,-82.292185,-25200.0
11990,74717,"@30ShadesOfCrazy - PT'S , but this bartender t...",640292474196377605,Sat Sep 05 22:36:36 +0000 2015,36.129459,-115.384091,-18000.0
14090,22306,@slimequeen_ yea or the new trashy hillbilly b...,644997380257910784,Fri Sep 18 22:12:13 +0000 2015,43.725479,-91.274654,-14400.0
37368,46980,You treat an outside wound with rubbing alcoho...,640681387775754240,Mon Sep 07 00:22:00 +0000 2015,47.283622,-122.181441,-25200.0
84140,53504,2 people shot to death near Manson: Two people...,641391590871691264,Tue Sep 08 23:24:06 +0000 2015,47.495315,-122.436232,-25200.0
15067,35729,join us tonight w/ DJ Juice for #drinks #frien...,646765720337051649,Wed Sep 23 19:18:58 +0000 2015,25.972852,-80.207046,-14400.0
18194,130482,Just getting my happy on #IGotKickedOutForThis...,640372856627556352,Sun Sep 06 03:56:01 +0000 2015,39.832013,-83.200169,-14400.0
31846,75435,@mmm_dog it's so fucking annoying i'm pretty s...,639101119776452608,Wed Sep 02 15:42:35 +0000 2015,34.126875,-119.061758,-25200.0
38415,126225,@Skip_Bedell @adamcarolla @AlisonBedell @spike...,640704684412440577,Mon Sep 07 01:54:35 +0000 2015,38.722982,-98.240424,NaN
55509,48716,when u are still so drunk and Mel's dad is her...,647418116000104449,Fri Sep 25 14:31:21 +0000 2015,39.643100,-75.788669,-18000.0
67415,5989,Camden NJ 7/Sylvan St 45 make shot in leg to C...,642671006511988738,Sat Sep 12 12:08:02 +0000 2015,39.878213,-75.134450,-18000.0
22078,78094,@BalconyLife_ * Gun shots *,640418100882509824,Sun Sep 06 06:55:48 +0000 2015,29.141956,-98.778559,NaN
95328,10061,@DanielleWBZ4 is the allergy report high agai...,641558120066609152,Wed Sep 09 10:25:50 +0000 2015,42.478356,-70.897823,NaN
12262,62005,But I'm in Austin about to get wasted ðŸ˜›,644987485840281600,Fri Sep 18 21:32:54 +0000 2015,30.127892,-97.928935,-21600.0
53668,30931,I Need a wine night ASAP ðŸ�·,639428570973085696,Thu Sep 03 13:23:45 +0000 2015,27.809790,-82.816110,NaN
66730,52338,We're giving away a free night at @AlbemarleEs...,644171435569741828,Wed Sep 16 15:30:13 +0000 2015,36.540739,-83.675290,-18000.0

In [17]:
filtered['random_number'] = filtered.text.apply(hash)

C:\Users\Tom Work\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [32]:
filtered['_id'] = filtered.id
filtered.index = filtered['_id']

C:\Users\Tom Work\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [33]:
pickle.dump(filtered, open('pickles/amt-sept.p', 'wb'))

In [34]:
import os
def make_batch(pickled_df, size, output_dir):
    """
    pickled_df: unlabeled data with 'random_number' column
    size: # of items batch to be created
    output_dir: where the outputs are saved
    """
    # Load data
    X = pickle.load(open(pickled_df, 'rb'))
    
    # select size subset
    batch = X.sort_values(by='random_number').head(size)
    
    # process for turk
    batch["text"] = batch.text.str.encode("utf-8")
    date = str(datetime.date.today())
    time = datetime.datetime.now().time()
    key = batch.iloc[0].random_number
    
    # persist
    description = "/c_amt {} {}h{}m {}".format(date, time.hour, time.minute, key)
    if not os.path.exists(output_dir + description):
        os.makedirs(output_dir + description)
    batch[["_id", "text", "random_number"]].to_csv(output_dir + description +  description + '.csv')
    pickle.dump(batch, open(output_dir + description + description +".p", 'wb'))
    X = X.drop(batch.index)
    pickle.dump(X, open(pickled_df, 'wb'))

In [35]:
make_batch('pickles/amt-sept.p', 1000, 'amt')

In [40]:
make_batch('pickles/amt-sept.p', 2000, 'amt')